config/routes.rb
Rails.application.routes.draw do
  

  root to: 'auth#login'
  post  'login',  to: 'auth#login_do', as: 'login'
  match 'logout', to: 'auth#logout', via: [:get, :post], as: 'logout'


  get 'app/setup',        to: 'nexmo_app#setup',        as: 'app_setup'
  post 'app/create',      to: 'nexmo_app#create',       as: 'app_create'
  get 'app/reset',        to: 'nexmo_app#reset',        as: 'app_reset'
  get  'app',             to: 'nexmo_app#show',         as: 'app'
  get  'app/edit',        to: 'nexmo_app#edit',         as: 'app_edit'
  post 'app/update',      to: 'nexmo_app#update',       as: 'app_update'
  get  'app/private_key', to: 'nexmo_app#private_key',  as: 'app_private_key'
  get  'app/public_key',  to: 'nexmo_app#public_key',   as: 'app_public_key'

  post 'app/ncco/custom',   to: 'nexmo_app#update_ncco_custom',  as: 'app_ncco_custom'
  post 'app/ncco/inbound',  to: 'nexmo_app#update_ncco_inbound',  as: 'app_ncco_inbound'
  post 'app/ncco/outbound', to: 'nexmo_app#update_ncco_outbound', as: 'app_ncco_outbound'
  post 'app/ncco/ivr',      to: 'nexmo_app#update_ncco_ivr',      as: 'app_ncco_ivr'
  post 'app/ncco/whisper',  to: 'nexmo_app#update_ncco_whisper',  as: 'app_ncco_whisper'
  post 'app/ncco/queue',    to: 'nexmo_app#update_ncco_queue',    as: 'app_ncco_queue'

  get  'numbers',                         to: 'numbers#index',    as: 'numbers'
  get  'numbers/search',                  to: 'numbers#search',   as: 'numbers_search_get'
  post 'numbers/search',                  to: 'numbers#search',   as: 'numbers_search'
  post 'numbers/buy',                     to: 'numbers#buy',      as: 'numbers_buy'
  post 'numbers/add/:country/:msisdn',    to: 'numbers#add',      as: 'numbers_add'
  post 'numbers/remove/:country/:msisdn', to: 'numbers#remove',   as: 'numbers_remove'


  resources :users, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :jwt
    end
  end

  get 'events',       to: 'events#index',   as: 'events'
  get 'events/raw',   to: 'events#raw',     as: 'events_raw'


  get  'api',         to: 'api#index', as: 'api'
  post 'api/jwt',     to: 'api#jwt'
  post 'api/users',   to: 'api#users'
  post 'api/ncco',    to: 'api#ncco'
  post  'api/whisper', to: 'api#whisper'
  post  'api/queue',   to: 'api#queue_conversations'
  post  'api/queue/transfer',   to: 'api#queue_transfer'
  post  'api/queue/ncco',   to: 'api#queue_ncco'


  get  'webhooks/answer', to: 'webhooks#answer',    as: 'webhooks_answer'
  get  'webhooks/answer_queue_transfer', to: 'webhooks#answer_queue_transfer',    as: 'webhooks_answer_queue_transfer'
  post 'webhooks/event',  to: 'webhooks#event',     as: 'webhooks_event'
  post 'webhooks/dtmf',  to: 'webhooks#dtmf',     as: 'webhooks_dtmf'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController

  def index
    @available_numbers = NexmoApi.numbers(session[:api_key], session[:api_secret])
  end

  def search
    @country = params[:country] || "GB"
    @available_numbers = NexmoApi.number_search(@country, session[:api_key], session[:api_secret])
  end

  def buy
    redirect_to numbers_url and return if (params[:country].blank? || params[:msisdn].blank?)
    if NexmoApi.number_buy(params[:country], params[:msisdn], session[:api_key], session[:api_secret])
      redirect_to numbers_url, notice: "#{params[:msisdn]} was successfully purchased."
    else
      redirect_to numbers_url, alert: "#{params[:msisdn]} could not be purchased."
    end
  end

  def add
    redirect_to numbers_url and return if (params[:country].blank? || params[:msisdn].blank?)
    unless @nexmo_app.number_msisdn.blank?
      NexmoApi.number_remove(@nexmo_app.app_id, @nexmo_app.number_country, @nexmo_app.number_msisdn, session[:api_key], session[:api_secret])
    end
    if NexmoApi.number_add(@nexmo_app.app_id, params[:country], params[:msisdn], session[:api_key], session[:api_secret])
      @nexmo_app.update(number_msisdn: params[:msisdn], number_country: params[:country])
      redirect_to numbers_url, notice: "#{params[:msisdn]} was successfully assigned to the app."
    else
      redirect_to numbers_url, alert: "#{params[:msisdn]} could not be assigned to the app."
    end
  end

  def remove
    redirect_to numbers_url and return if (params[:country].blank? || params[:msisdn].blank?)
    if NexmoApi.number_remove(@nexmo_app.app_id, params[:country], params[:msisdn], session[:api_key], session[:api_secret])
      @nexmo_app.update(number_msisdn: nil, number_country: nil)
      redirect_to numbers_url, notice: "#{params[:msisdn]} was successfully removed from the app."
    else
      redirect_to numbers_url, alert: "#{params[:msisdn]} could not be removed from the app."
    end
  end

end

app/views/numbers/_search_form.html.erb
    <%= form_tag (numbers_search_path) do %>
      Buy number in 
      <%= select_tag(:country, options_for_select(["GB", "USA", "FR"], country)) %>
      <%= submit_tag("Search", class: 'btn btn-sm btn-primary') %>
    <% end %>

app/views/numbers/index.html.erb
<div class="row mb-4">
  <div class="col-12 col-lg-6">
    <h1>Numbers</h1>
    <% unless @nexmo_app.number_msisdn.blank? %>
      <h4>Number in use: <%= @nexmo_app.number_msisdn %> (<%= @nexmo_app.number_country %>)</h4>
    <% end %>
  </div>
  <div class="col-12 col-lg-6 text-lg-right">
    <%= render partial: "search_form", locals: {country: 'GB'} %>
  </div>
</div>

<% if @available_numbers.count == 0 %>
  <p class="alert alert-danger">Please <%= link_to "purchase a number", numbers_search_get_path %> first.</p>
<% else %>

  <% if @nexmo_app.number_msisdn.blank? %>
    <p class="alert alert-info">No Number in use</p>
  <% end %>

  <hr />

  <table class="table table-sm table-borderless table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Available Number</th>
            <th scope="col">Country</th>
            <th scope="col">Features</th>
            <th scope="col">&nbsp;</th>
          </tr>
        </thead>

        <tbody>
          <% @available_numbers.each do |number| %>
            <tr>
              <td><%= number.msisdn %></td>
              <td><%= number.country %></td>
              <td><%= number.features %></td>
              <td>
                <% if !number.features.include?("VOICE") %>
                  No voice capability.
                <% elsif number.voiceCallbackValue.blank? %>
                  <%= link_to "Link", numbers_add_path(country: number.country, msisdn: number.msisdn), method: :post, class: 'btn btn-sm btn-danger' %>
                <% elsif number.voiceCallbackValue == @nexmo_app.app_id %>
                  <strong>Linked.</strong>
                  <%= link_to "Unlink", numbers_remove_path(country: number.country, msisdn: number.msisdn), method: :post, class: 'btn btn-sm btn-warning' %>
                <% else %>
                  Number already in use.
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

<% end %>

app/views/numbers/search.html.erb
<div class="row">
  <div class="col-6">
    <h1>Numbers Available in <%= @country %> </h1>
  </div>
  <div class="col-6 text-right">
    <%= render partial: "search_form", locals: {country: @country} %>
  </div>
</div>

<% if @available_numbers.blank? %>
  <p>Sorry, no numbers found.</p>
<% else %>
  <table class="table table-sm table-borderless table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Number</th>
        <th scope="col">Country</th>
        <th scope="col">Features</th>
        <th scope="col">Type</th>
        <th scope="col">Cost</th>
        <th scope="col">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @available_numbers.each do |number| %>
        <tr>
          <td><%= number.msisdn %></td>
          <td><%= number.country %></td>
          <td><%= number.features %></td>
          <td><%= number.type %></td>
          <td>&euro; <%= number.cost %></td>
          <td>
            <%= form_tag (numbers_buy_path) do %>
            <%= hidden_field_tag(:country, @country) %>
            <%= hidden_field_tag(:msisdn, number.msisdn) %>
            <%= submit_tag("Buy", class: 'btn btn-sm btn-primary') %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>