config/routes.rb
Rails.application.routes.draw do
  

  root to: 'auth#login'
  post  'login',  to: 'auth#login_do', as: 'login'
  match 'logout', to: 'auth#logout', via: [:get, :post], as: 'logout'


  get 'app/setup',        to: 'nexmo_app#setup',        as: 'app_setup'
  post 'app/create',      to: 'nexmo_app#create',       as: 'app_create'
  get 'app/reset',        to: 'nexmo_app#reset',        as: 'app_reset'
  get  'app',             to: 'nexmo_app#show',         as: 'app'
  get  'app/edit',        to: 'nexmo_app#edit',         as: 'app_edit'
  post 'app/update',      to: 'nexmo_app#update',       as: 'app_update'
  get  'app/private_key', to: 'nexmo_app#private_key',  as: 'app_private_key'
  get  'app/public_key',  to: 'nexmo_app#public_key',   as: 'app_public_key'

  post 'app/ncco/custom',   to: 'nexmo_app#update_ncco_custom',  as: 'app_ncco_custom'
  post 'app/ncco/inbound',  to: 'nexmo_app#update_ncco_inbound',  as: 'app_ncco_inbound'
  post 'app/ncco/outbound', to: 'nexmo_app#update_ncco_outbound', as: 'app_ncco_outbound'
  post 'app/ncco/ivr',      to: 'nexmo_app#update_ncco_ivr',      as: 'app_ncco_ivr'
  post 'app/ncco/whisper',  to: 'nexmo_app#update_ncco_whisper',  as: 'app_ncco_whisper'
  post 'app/ncco/queue',    to: 'nexmo_app#update_ncco_queue',    as: 'app_ncco_queue'

  get  'numbers',                         to: 'numbers#index',    as: 'numbers'
  get  'numbers/search',                  to: 'numbers#search',   as: 'numbers_search_get'
  post 'numbers/search',                  to: 'numbers#search',   as: 'numbers_search'
  post 'numbers/buy',                     to: 'numbers#buy',      as: 'numbers_buy'
  post 'numbers/add/:country/:msisdn',    to: 'numbers#add',      as: 'numbers_add'
  post 'numbers/remove/:country/:msisdn', to: 'numbers#remove',   as: 'numbers_remove'


  resources :users, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :jwt
    end
  end

  get 'events',       to: 'events#index',   as: 'events'
  get 'events/raw',   to: 'events#raw',     as: 'events_raw'


  get  'api',         to: 'api#index', as: 'api'
  post 'api/jwt',     to: 'api#jwt'
  post 'api/users',   to: 'api#users'
  post 'api/ncco',    to: 'api#ncco'
  post  'api/whisper', to: 'api#whisper'
  post  'api/queue',   to: 'api#queue_conversations'
  post  'api/queue/transfer',   to: 'api#queue_transfer'
  post  'api/queue/ncco',   to: 'api#queue_ncco'


  get  'webhooks/answer', to: 'webhooks#answer',    as: 'webhooks_answer'
  get  'webhooks/answer_queue_transfer', to: 'webhooks#answer_queue_transfer',    as: 'webhooks_answer_queue_transfer'
  post 'webhooks/event',  to: 'webhooks#event',     as: 'webhooks_event'
  post 'webhooks/dtmf',  to: 'webhooks#dtmf',     as: 'webhooks_dtmf'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  validates :user_id, uniqueness: true
  validates :user_name, uniqueness: true

  def generate_jwt(nexmo_app)
    rsa_private = OpenSSL::PKey::RSA.new(nexmo_app.private_key)
    expiry_time = Time.now.to_i + 86400       # 1 day
    payload = {
      "application_id": nexmo_app.app_id,
      "iat": Time.now.to_i,
      "jti": SecureRandom.uuid,
      "sub": self.user_name,
      "exp": expiry_time,   
      "acl": {
        "paths": {
          "/**": {}
        }
      }
    }
    new_token = JWT.encode payload, rsa_private, 'RS256'
    self.update(jwt: new_token, jwt_expires_at: Time.at(expiry_time))
  end

  def self.retrieve_all(nexmo_app)
    existing_users = User.all
    user_ids_to_remove = existing_users.map { |u| u.id }
    api_users = NexmoApi.users(nexmo_app)
    api_users.each do |api_user|
      existing_user = User.find_by(user_name: api_user.name)
      puts existing_user.inspect
      if existing_user.blank?
        User.create(user_id: api_user.id, user_name: api_user.name)
      else 
        existing_user.update(user_id: api_user.id, user_name: api_user.name)
        user_ids_to_remove.delete(existing_user.id)
      end
    end
    user_ids_to_remove.each do |id|
      existing_user = User.find_by(id: id)
      existing_user.destroy unless existing_user.blank?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :jwt, :edit, :update, :destroy]

  private 

  def set_user
    @user = User.find(params[:id])
  end


  public

  def index
    User.retrieve_all(@nexmo_app)
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if !@user.user_name.blank? && NexmoApi.create_user(@user.user_name, @nexmo_app) && @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if !NexmoApi.delete_user(@user, @nexmo_app)
      redirect_to users_path, notice: 'User could not be destroyed.'
      return
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def jwt
    if @nexmo_app.private_key.blank?
      redirect_to user_path(@user), notice: 'Your Nexmo app does not have a private key'
    end
    @user.generate_jwt(@nexmo_app)
    redirect_to user_path(@user), notice: 'User JWT was successfully created.'
  end


  private 
  def user_params
    params.require(:user).permit(:user_name)
  end

end

app/views/users/_form.html.erb
<div class="">
  <%= form_with(model: [user], local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :user_name %>
      <%= form.text_field :user_name, class:"form-control" %>
    </div>

    <div class="actions">
      <% if user.id.blank? %>
        <%= form.submit "Create", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', users_path, class: 'btn btn-secondary' %>
      <% else %>
        <%= form.submit "Update", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', users_path, class: 'btn btn-secondary' %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-6">
    <h1>Users</h1>
  </div>
  <div class="col-6 text-right">
    <%= link_to 'New User', new_user_path, class: 'btn btn-sm btn-outline-primary' %>
  </div>
</div>


<div class="row mt-4">
  <div class="col-12">
    <% if @users.count == 0 %>
      <p>None.</p>
    <% else %>
      <table class="table table-sm table-borderless table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">User id</th>
            <th scope="col">User name</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.user_id %></td>
              <td><%= link_to user.user_name, user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="col"><div class="col-12 col-lg-6">
  <%= render 'form', user: @user %>
</div></div>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <strong>User id:</strong>
  <%= @user.user_id || 'not set' %>
</p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name || 'not set' %>
</p>

<p>
  <strong>JWT:</strong>
  <%= @user.jwt %>
</p>

<p>
  <strong>JWT expires at:</strong>
  <%= @user.jwt_expires_at %>
</p>


  <%= link_to 'View all users', users_path, class: 'btn btn-outline-primary' %>
  <%= button_to 'Generate JWT', jwt_user_path(@user), class: 'btn btn-outline-warning' %>
  <%= link_to 'Destroy', [@user], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>