config/routes.rb
Rails.application.routes.draw do
  

  root to: 'auth#login'
  post  'login',  to: 'auth#login_do', as: 'login'
  match 'logout', to: 'auth#logout', via: [:get, :post], as: 'logout'


  get 'app/setup',        to: 'nexmo_app#setup',        as: 'app_setup'
  post 'app/create',      to: 'nexmo_app#create',       as: 'app_create'
  get 'app/reset',        to: 'nexmo_app#reset',        as: 'app_reset'
  get  'app',             to: 'nexmo_app#show',         as: 'app'
  get  'app/edit',        to: 'nexmo_app#edit',         as: 'app_edit'
  post 'app/update',      to: 'nexmo_app#update',       as: 'app_update'
  get  'app/private_key', to: 'nexmo_app#private_key',  as: 'app_private_key'
  get  'app/public_key',  to: 'nexmo_app#public_key',   as: 'app_public_key'

  post 'app/ncco/custom',   to: 'nexmo_app#update_ncco_custom',  as: 'app_ncco_custom'
  post 'app/ncco/inbound',  to: 'nexmo_app#update_ncco_inbound',  as: 'app_ncco_inbound'
  post 'app/ncco/outbound', to: 'nexmo_app#update_ncco_outbound', as: 'app_ncco_outbound'
  post 'app/ncco/ivr',      to: 'nexmo_app#update_ncco_ivr',      as: 'app_ncco_ivr'
  post 'app/ncco/whisper',  to: 'nexmo_app#update_ncco_whisper',  as: 'app_ncco_whisper'
  post 'app/ncco/queue',    to: 'nexmo_app#update_ncco_queue',    as: 'app_ncco_queue'

  get  'numbers',                         to: 'numbers#index',    as: 'numbers'
  get  'numbers/search',                  to: 'numbers#search',   as: 'numbers_search_get'
  post 'numbers/search',                  to: 'numbers#search',   as: 'numbers_search'
  post 'numbers/buy',                     to: 'numbers#buy',      as: 'numbers_buy'
  post 'numbers/add/:country/:msisdn',    to: 'numbers#add',      as: 'numbers_add'
  post 'numbers/remove/:country/:msisdn', to: 'numbers#remove',   as: 'numbers_remove'


  resources :users, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :jwt
    end
  end

  get 'events',       to: 'events#index',   as: 'events'
  get 'events/raw',   to: 'events#raw',     as: 'events_raw'


  get  'api',         to: 'api#index', as: 'api'
  post 'api/jwt',     to: 'api#jwt'
  post 'api/users',   to: 'api#users'
  post 'api/ncco',    to: 'api#ncco'
  post  'api/whisper', to: 'api#whisper'
  post  'api/queue',   to: 'api#queue_conversations'
  post  'api/queue/transfer',   to: 'api#queue_transfer'
  post  'api/queue/ncco',   to: 'api#queue_ncco'


  get  'webhooks/answer', to: 'webhooks#answer',    as: 'webhooks_answer'
  get  'webhooks/answer_queue_transfer', to: 'webhooks#answer_queue_transfer',    as: 'webhooks_answer_queue_transfer'
  post 'webhooks/event',  to: 'webhooks#event',     as: 'webhooks_event'
  post 'webhooks/dtmf',  to: 'webhooks#dtmf',     as: 'webhooks_dtmf'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nexmo_app.rb
require "redis"


class NexmoApp < ApplicationRecord

  validates :name, presence: true
  enum voice_answer_type: [:custom, :inbound_call, :outbound_call, :ivr, :call_whisper, :call_queue]
  

  def voice_answer_ncco_descriptive(params)
    client = Redis.new
    
    case self.voice_answer_type 
    when "custom"
      '<h5>Custom NCCO &nbsp; <a href="/app/edit" class="btn btn-outline-primary btn-sm">Edit</a></h5><pre>' + self.voice_answer_custom_ncco + "</pre>"
    when "inbound_call"
      "<h5>Inbound call</h5><pre>" + Ncco.inbound + "</pre>"
    when "outbound_call"
      "<h5>Outbound call</h5><pre>" + Ncco.outbound(self) + "</pre>"
    when "ivr"
      "<h5>IVR - Main menu</h5><pre>" + Ncco.ivr(self, params[:webhooks_dtmf_url]) + "</pre>" +
      "<h5>Jane selection</h5><pre>" + Ncco.ivr_jane + "</pre>" +
      "<h5>Joe selection</h5><pre>" + Ncco.ivr_joe + "</pre>"
    when "call_whisper"
      "<h5>Call whisper</h5>" +
      "<pre>CONVERSATION_ID: " + (client.get("whisper_conversation_id") || "-") + 
      "\nAGENT_LEG_ID: " + (client.get("whisper_agent_leg_id") || "-" ) +
      "\nSUPERVISOR_LEG_ID: " + (client.get("whisper_supervisor_leg_id") || "-") +
      "\nCUSTOMER_LEG_ID: " + (client.get("whisper_customer_leg_id") || "-") +
      "</pre>"+
      "<h6>Customer</h6><pre>" + Ncco.call_whisper_customer(params[:server_url]) + "</pre>" +
      "<h6>Agent</h6><pre>" + Ncco.call_whisper_agent(params[:server_url]) + "</pre>" +
      "<h6>Supervisor</h6><pre>" + Ncco.call_whisper_supervisor(params[:server_url]) + "</pre>"
    when "call_queue"
      "<h5>Call Queueing</h5>" +
      "<h6>Queued Calls: </h6><pre>" + (client.get("queue_conversations") || "").split(" || ").join("\n") +
      "</pre>"+
      "<h6>Customer NCCO</h6><pre>" + Ncco.call_queue_customer(params[:server_url]) + "</pre>" +
      "<h6>Customer connect NCCO</h6><pre>" + Ncco.call_queue_customer_connect + "</pre>" +
      "<h6>Agent NCCO</h6><pre>" + Ncco.call_queue_agent + "</pre>"
    else 
      "<h5>Not set</h5>"
    end
  end

  def voice_answer_ncco(params)
    case self.voice_answer_type 
    when "custom"
      self.voice_answer_custom_ncco
    when "inbound_call"
      Ncco.inbound
    when "outbound_call"
      Ncco.outbound(self)
    when "ivr"
      Ncco.ivr(self, params[:webhooks_dtmf_url])
    else 
      ""
    end
  end


end

app/controllers/nexmo_app_controller.rb
require "redis"

class NexmoAppController < ApplicationController
  skip_before_action :set_nexmo_app, only: [:setup, :create, :reset]


  def edit
    @dtmf_url = webhooks_dtmf_url
  end


  def update
    if @nexmo_app.update(nexmo_app_params)
      redirect_to app_url, notice: 'App was successfully updated.'
      return
    end
    render action: :edit, alert: 'Something went wrong' and return
  end



  # APP KEYS

  def public_key
    send_data @nexmo_app.public_key,
      :disposition => "attachment; filename=public.key"
  end
  def private_key
    send_data @nexmo_app.private_key,
      :disposition => "attachment; filename=private.key"
  end



  # APP SETUP

  def setup
    if NexmoApp.all.count > 0
      redirect_to app_url and return
    end
    @nexmo_app = NexmoApp.new
  end

  def create
    key = OpenSSL::PKey::RSA.generate(2048)
    @nexmo_app = NexmoApp.new(nexmo_app_params.merge({
      voice_answer_url: webhooks_answer_url, voice_answer_method: "GET",
      voice_event_url: webhooks_event_url, voice_event_method: "POST",
      public_key: key.public_key, private_key: key.to_s
    }))
    unless @nexmo_app.save
      render action: :setup, alert: 'Something went wrong' and return
    end
    unless NexmoApi.app_create(@nexmo_app, session[:api_key], session[:api_secret])
      redirect_to app_url, alert: 'Nexmo app was successfully created but could not be updated on the Nexmo servers.'
      return
    end
    redirect_to app_url, notice: "Nexmo app was successfully created."
  end

  def reset
    EventLog.destroy_all
    User.destroy_all
    NexmoApp.destroy_all
    redirect_to app_setup_url
  end


  # NCCO updates

  def update_ncco_custom
    @nexmo_app.update(voice_answer_type: :custom)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end

  def update_ncco_inbound
    @nexmo_app.update(voice_answer_type: :inbound_call)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end

  def update_ncco_outbound
    @nexmo_app.update(voice_answer_type: :outbound_call)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end

  def update_ncco_ivr
    @nexmo_app.update(voice_answer_type: :ivr)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end
  def update_ncco_whisper
    client = Redis.new
    client.del("whisper_conversation_id")
    client.del("whisper_agent_leg_id")
    client.del("whisper_supervisor_leg_id")
    client.del("whisper_customer_leg_id")
    @nexmo_app.update(voice_answer_type: :call_whisper)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end

  def update_ncco_queue
    client = Redis.new
    client.del("queue_conversations")
    @nexmo_app.update(voice_answer_type: :call_queue)
    redirect_to app_url, notice: "NCCO was successfully updated."
  end


  private

  def nexmo_app_params
    params.require(:nexmo_app).permit(:name, :voice_answer_type, :voice_answer_custom_ncco)
  end

end

app/views/nexmo_app/edit.html.erb
<h1 class="h3 mt-4 text-center"><%= @nexmo_app.name %></h1>
<h4 class="h6 text-center"><%= @nexmo_app.app_id %></h6>


<%= form_with(url: app_update_path, local: true) do |form| %>
  <% if @nexmo_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nexmo_app.errors.count, "error") %> prohibited this Nexmo app from being saved:</h2>

      <ul>
      <% @nexmo_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8 text-center">
      <div class="form-group">
        <h3 class="mt-4">Custom Answer NCCO</h3>
        <%= form.text_area "nexmo_app[voice_answer_custom_ncco]", id: 'voice_answer_custom_ncco', rows: 20, value: @nexmo_app.voice_answer_custom_ncco, class:"form-control pre", required: true %>
      </div>

      <%= form.submit "Update", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', app_path, class: 'btn btn-secondary' %>

    </div>
  </div>

<% end %>

app/views/nexmo_app/setup.html.erb
<% title "Setup" %>

<h1 class="h2 text-center mb-4">New Application setup</h1>

<%= form_with(url: app_create_path, local: true) do |form| %>
  <% if @nexmo_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nexmo_app.errors.count, "error") %> prohibited this Nexmo app from being saved:</h2>
      <ul>
      <% @nexmo_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4 col-xl-3 text-center">
      <div class="form-group">
        <%= form.text_field "nexmo_app[name]", class:"form-control", value: @nexmo_app.name, placeholder: "Application name", required: true %>
      </div>

       <%= form.submit "Create", class: 'btn btn-primary mt-2' %>
    </div>
  </div>
<% end %>

app/views/nexmo_app/show.html.erb
<div class="float-md-right">
  <%= link_to raw('<i class="fas fa-download"></i> Private key'), app_private_key_path, class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to raw('<i class="fas fa-download"></i> Public key'), app_public_key_path, class: 'btn btn-sm btn-outline-primary' %>
</div>

<h1 class="mb-5"><%= @nexmo_app.name %></h1>

<table class="table">
<tr>
  <th>App id</th>
  <td><%= @nexmo_app.app_id %></td>
</tr>
<tr>
  <th>App name</th>
  <td><%= @nexmo_app.name %></td>
</tr>
<tr>
  <th>Answer URL</th>
  <td>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text input-group-text-<%= (@nexmo_app.voice_answer_method || "").downcase %>"><%= @nexmo_app.voice_answer_method %></div>
      </div>
      <%= link_to @nexmo_app.voice_answer_url, webhooks_answer_path, class: 'form-control form-control-url', target: '_blank' %>
    </div>
  </td>
</tr>
<tr>
  <th>Voice Event  URL</th>
  <td>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text input-group-text-<%= (@nexmo_app.voice_event_method || "").downcase %>"><%= @nexmo_app.voice_event_method %></div>
      </div>
      <span class="form-control form-control-url"><%= @nexmo_app.voice_event_url %></span>
    </div>
  </td>
</tr>
<tr>
  <th>Phone number</th>
  <td>
    <% if @nexmo_app.number_msisdn.blank? %>
      <%= link_to raw('<i class="fas fa-plus"></i> Add'), numbers_path, class: 'btn btn-outline-primary btn-sm' %>
    <% else %>
      <%= @nexmo_app.number_msisdn %> (<%= @nexmo_app.number_country %>)
    <% end %>
  </td>
</tr>
<tr>
  <th>NCCO</th>
  <td>
    <p>Change for: 
      <%= link_to "Custom", app_ncco_custom_path, method: :post, class: 'btn btn' + ( @nexmo_app.custom? ? '' : '-outline') + '-primary btn-sm' %>
      <%= link_to "Inbound Call", app_ncco_inbound_path, method: :post, class: 'btn btn' + ( @nexmo_app.inbound_call? ? '' : '-outline') + '-primary btn-sm' %>
      <%= link_to "Outbound Call", app_ncco_outbound_path, method: :post, class: 'btn btn' + ( @nexmo_app.outbound_call? ? '' : '-outline') + '-primary btn-sm' %>
      <%= link_to "IVR", app_ncco_ivr_path, method: :post, class: 'btn btn' + ( @nexmo_app.ivr? ? '' : '-outline') + '-primary btn-sm' %>
      <!--
      <%= link_to "Call Whisper", app_ncco_whisper_path, method: :post, class: 'btn btn' + ( @nexmo_app.call_whisper? ? '' : '-outline') + '-primary btn-sm' %>
      -->
      <%= link_to "Call Queueing", app_ncco_queue_path, method: :post, class: 'btn btn' + ( @nexmo_app.call_queue? ? '' : '-outline') + '-primary btn-sm' %>
    </p>
    <%= raw @nexmo_app.voice_answer_ncco_descriptive({webhooks_dtmf_url: webhooks_dtmf_url, server_url: root_url}) %>
  </td>
</tr>
</table>


<!-- 
<a href="/reset">reset</a>


<%= @nexmo_app.inspect %>

-->