config/routes.rb
Rails.application.routes.draw do
  

  root to: 'auth#login'
  post  'login',  to: 'auth#login_do', as: 'login'
  match 'logout', to: 'auth#logout', via: [:get, :post], as: 'logout'


  get 'app/setup',        to: 'nexmo_app#setup',        as: 'app_setup'
  post 'app/create',      to: 'nexmo_app#create',       as: 'app_create'
  get 'app/reset',        to: 'nexmo_app#reset',        as: 'app_reset'
  get  'app',             to: 'nexmo_app#show',         as: 'app'
  get  'app/edit',        to: 'nexmo_app#edit',         as: 'app_edit'
  post 'app/update',      to: 'nexmo_app#update',       as: 'app_update'
  get  'app/private_key', to: 'nexmo_app#private_key',  as: 'app_private_key'
  get  'app/public_key',  to: 'nexmo_app#public_key',   as: 'app_public_key'

  post 'app/ncco/custom',   to: 'nexmo_app#update_ncco_custom',  as: 'app_ncco_custom'
  post 'app/ncco/inbound',  to: 'nexmo_app#update_ncco_inbound',  as: 'app_ncco_inbound'
  post 'app/ncco/outbound', to: 'nexmo_app#update_ncco_outbound', as: 'app_ncco_outbound'
  post 'app/ncco/ivr',      to: 'nexmo_app#update_ncco_ivr',      as: 'app_ncco_ivr'
  post 'app/ncco/whisper',  to: 'nexmo_app#update_ncco_whisper',  as: 'app_ncco_whisper'
  post 'app/ncco/queue',    to: 'nexmo_app#update_ncco_queue',    as: 'app_ncco_queue'

  get  'numbers',                         to: 'numbers#index',    as: 'numbers'
  get  'numbers/search',                  to: 'numbers#search',   as: 'numbers_search_get'
  post 'numbers/search',                  to: 'numbers#search',   as: 'numbers_search'
  post 'numbers/buy',                     to: 'numbers#buy',      as: 'numbers_buy'
  post 'numbers/add/:country/:msisdn',    to: 'numbers#add',      as: 'numbers_add'
  post 'numbers/remove/:country/:msisdn', to: 'numbers#remove',   as: 'numbers_remove'


  resources :users, only: [:index, :new, :create, :show, :destroy] do
    member do
      post :jwt
    end
  end

  get 'events',       to: 'events#index',   as: 'events'
  get 'events/raw',   to: 'events#raw',     as: 'events_raw'


  get  'api',         to: 'api#index', as: 'api'
  post 'api/jwt',     to: 'api#jwt'
  post 'api/users',   to: 'api#users'
  post 'api/ncco',    to: 'api#ncco'
  post  'api/whisper', to: 'api#whisper'
  post  'api/queue',   to: 'api#queue_conversations'
  post  'api/queue/transfer',   to: 'api#queue_transfer'
  post  'api/queue/ncco',   to: 'api#queue_ncco'


  get  'webhooks/answer', to: 'webhooks#answer',    as: 'webhooks_answer'
  get  'webhooks/answer_queue_transfer', to: 'webhooks#answer_queue_transfer',    as: 'webhooks_answer_queue_transfer'
  post 'webhooks/event',  to: 'webhooks#event',     as: 'webhooks_event'
  post 'webhooks/dtmf',  to: 'webhooks#dtmf',     as: 'webhooks_dtmf'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<% if alert %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title><%= content_for?(:title) ? (yield(:title) + ' @ ') : '' %> Nexmo Contact Center</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<main role="main" class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light  border-bottom shadow-sm mb-4">
    <a href="/" class="navbar-brand"><%= image_tag 'nexmo.png', class: '', style: 'height:30px;' %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
        
      <ul class="navbar-nav">
        <% unless @nexmo_app.blank? %>
          <li class="nav-item"><%= link_to "App Settings", app_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Numbers", numbers_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Events", events_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "SDK Integration", api_path, class: "nav-link" %></li>
        <% end %>
        <li class="nav-item"><%= link_to "Log out", logout_path, class: "nav-link" %>
        <li class="nav-item"><span class="nav-link nav-balance">Balance:<br />
          €<%= number_with_precision(@balance, precision: 2) %></span></li>
      </ul>
    </div>
  </nav>


  <%= render partial: 'layouts/flashes' %>
  
  <%= yield %>  
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/simple.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<title><%= content_for?(:title) ? (yield(:title) + ' @ ') : '' %> Nexmo Contact Center</title>
</head>
<body>
<main role="main" class="container text-center">
  <%= yield %>
</main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>